[package]
name = "ns-router-rs"
version = "0.1.0"
edition = "2021"
description = "Neuro-symbolic router implementation"

[lib]
name = "ns_router_rs"
path = "src/lib.rs"

[dependencies]
# Add dependencies specific to this crate here
petgraph = "0.6"
dashmap = "5.5"
